cc_binary(
    name = "test_signed_udp",
    srcs = ["test_signed_udp.cc"],
    deps = [
        "//lib:endpoint",
    ],
)

cc_binary(
    name = "test_recv_udp",
    srcs = ["test_recv_udp.cc"],
    deps = [
        "//lib:endpoint",
    ],
)
