cc_binary(
    name = "bench_simple_rpc",
    srcs = ["bench_simple_rpc.cc"],
    deps = [
        "//lib:ooo_rpc_endpoint",
        "//lib:signature_provider",
        "//lib:hmac_provider",
    ],
)