# Proxy Info
clientId: 0
clientIp: "127.0.0.7"
clientKey: keys/clients/client0.pem

clientPort: 33000

# Receiver Info
replicaIps:
  - "127.0.0.1"
  - "127.0.0.2"
  - "127.0.0.3"
  - "127.0.0.4"
replicaKeysDir: "keys/replicas"
replicaPort: 34000

proxyPortBase: 31000
proxyIps:
  - "127.0.0.5"

