transport: nng 

app: kv_store

client:
  ips: 
  - "127.0.1.0"
  - "127.0.1.1"
  port: 33000
  keysDir: keys/client
  normalPathTimeout: 15000    # 15ms
  slowPathTimeout:   200000   # 200 ms
  requestTimeout: 10000000    # 10 s

  sendMode: "maxInFlight"
  maxInFlight: 5
  sendRate: 10 
  runtimeSeconds: 20
  requestSize: 512


# Proxy Info
proxy:
  ips: 
    - "127.0.0.9"  
    - "127.0.0.10"  
  shards: 1
  forwardPort: 31000
  measurementPort: 32000
  keysDir: keys/proxy
  maxOwd: 15000

# Receiver Info
receiver:
  ips: 
    - "127.0.0.5"
    - "127.0.0.6"
    - "127.0.0.7"
    - "127.0.0.8"
  port: 33000
  keysDir: keys/receiver
  shards: 1 # The number of threads to receive threads 
  local: false # Although it's local, we actually use distinct loopback addresses for localhost experiments
  numVerifyThreads: 2

# Replica Info
replica:
  ips: 
  - "127.0.0.1"
  - "127.0.0.2"
  - "127.0.0.3"
  - "127.0.0.4"
  port: 34000
  app: "counter"
  keysDir: "keys/replica"
  repairViewTimeout: 4000000
  repairTimeout: 50000
  numVerifyThreads: 1
  numSendThreads: 2
  checkpointInterval: 100

