transport: udp

client:
  ips: 
  - "127.0.1.0"
  - "127.0.1.1"
  port: 33000
  keysDir: keys/client
  maxRequests: 1
  numRequests: 100
  runtimeSeconds: 10 
  normalPathTimeout: 5000
  slowPathTimeout: 50000
  sendRate: 1000
  # the sendmode can be either using sendRate or maxRequests in flight. 
  sendMode: "sendRate"
  # sendMode: "maxRequests"
  # there may be 3 backpressure modes: none, sleep, adjust
  # none means no back pressure, sleep means sleep if outstanding requests are too many,
  # adjust means having the send rate commensurate with the send rate
  backPressure: "sleep"
  # how much time the sending event pause after each backpressure. The unit is in second. 
  sleepTime: 0.07


# Proxy Info
proxy:
  ips: 
    - "127.0.0.9"  
    - "127.0.0.10"  
  shards: 1
  forwardPort: 31000
  measurementPort: 32000
  keysDir: keys/proxy
  maxOwd: 15000

# Receiver Info
receiver:
  ips: 
    - "127.0.0.5"
    - "127.0.0.6"
    - "127.0.0.7"
    - "127.0.0.8"
  port: 33000
  keysDir: keys/receiver
  shards: 1 # The number of threads to receive threads 
  local: false # Although it's local, we actually use distinct loopback addresses for localhost experiments

# Replica Info
replica:
  ips: 
  - "127.0.0.1"
  - "127.0.0.2"
  - "127.0.0.3"
  - "127.0.0.4"
  port: 34000
  keysDir: "keys/replica"
  fallbackTimeout: 200000
  fallbackStartTimeout: 50000

