transport: nng

app: "counter"

client:
  ips: 
  - "127.0.1.0"
  port: 33000
  keysDir: keys/client
  normalPathTimeout: 100000   # 100 ms
  slowPathTimeout:   1000000  # 1 s

  sendMode: "sendRate"
  maxInFlight: 500
  sendRate: 2000
  runtimeSeconds: 15


# Proxy Info
proxy:
  ips: 
    - "127.0.0.9"
  shards: 1
  forwardPort: 31000
  measurementPort: 32000
  keysDir: keys/proxy
  maxOwd: 15000

# Receiver Info
receiver:
  ips: 
    - "127.0.0.5"
  port: 33000
  keysDir: keys/receiver
  shards: 1 # The number of threads to receive threads 
  local: false # Although it's local, we actually use distinct loopback addresses for localhost experiments

# Replica Info
replica:
  ips: 
  - "127.0.0.1"
  port: 34000
  app: "counter"
  keysDir: "keys/replica"
  fallbackTimeout: 200000
  fallbackStartTimeout: 50000

