# Proxy Info
proxyId: 0
proxyIp: "127.0.0.5"
proxyNumShards: 1
proxyForwardPortBase: 31000
proxyMeasurementPort: 32000
proxyKey: keys/proxies/proxy0.pem

# Receiver Info
receiverIps:
  - "127.0.0.6"
receiverShards: 1 # The number of threads to receive threads
receiverPort: 33000 # The port is exposed to client/proxy and is used to receive client/proxy requests.

initialOwd: 1000 # The initial one-way delay (usecs) between replicas and proxies
maxOwd: 5000

numClients: 2
clientPubKeyPrefix: ""