# Receiver Info
receiverId: 0
receiverIp: "127.0.0.6"
receiverKey: keys/receivers/receiver0.pem
receiverPort: 33000

# Proxy info
numProxies: 1
proxyMeasurementPort: 32000
proxyPubKeyPrefix: "keys/proxies"

# Ips of replica this receiever forwards to, NOT all replicas.
replicaIps:
  - "127.0.0.1"

replicaPort: 34000