transport: nng 

app: "kv_store"

client:
  ips:
  - 10.138.0.6
  - 10.182.0.4
  - 10.142.0.4
  - 10.150.0.9
  # - 10.138.0.8
  # - 10.182.0.6
  # - 10.142.0.6
  # - 10.150.0.3

  keysDir: keys/client
  maxInFlight: 100
  port: 33000
  runtimeSeconds: 22
  
  sendMode: maxInFlight
  maxInFlight: 100
  sendRate: 300
  requestSize: 512

  normalPathTimeout: 200000
  slowPathTimeout: 1000000

proxy:
  forwardPort: 31000
  ips:
  - 10.138.0.7
  - 10.182.0.5
  - 10.142.0.5
  - 10.150.0.10
  keysDir: keys/proxy
  maxOwd: 100000
  measurementPort: 32000
  shards: 1

receiver:
  ips:
  - 10.138.0.4
  - 10.182.0.2
  - 10.142.0.2
  - 10.150.0.8
  keysDir: keys/receiver
  local: true
  numVerifyThreads: 6
  port: 33000
  shards: 1

replica:
  fallbackStartTimeout: 5000000
  fallbackTimeout: 10000000
  ips:
  - 10.138.0.4
  - 10.182.0.2
  - 10.142.0.2
  - 10.150.0.8
  keysDir: keys/replica
  numSendThreads: 6
  numVerifyThreads: 6
  port: 34000
