transport: "udp"

client:
  ips:
  - "10.128.0.13"
  - "10.128.0.5"
  port: 33000
  keysDir: keys/client
  maxRequests: 1
  numRequests: 1000000
  runtimeSeconds: 60 
  normalPathTimeout: 5000
  slowPathTimeout: 500000
  sendRate: 100
  # the sendmode can be either using sendRate or maxRequests in flight. 
  sendMode: "sendRate"
  # sendMode: "maxRequests"
  # there may be 3 backpressure modes: none, sleep, adjust
  # none means no back pressure, sleep means sleep if outstanding requests are too many,
  # adjust means having the send rate commensurate with the send rate
  backPressure: "sleep"
  # how much time the sending event pause after each backpressure. The unit is in second. 
  sleepTime: 0.07  

# Proxy Info
proxy:
  ips: 
    - "10.128.0.17"  
    - "10.128.0.19"  
    - "10.128.0.21"
    - "10.128.0.22"    
  shards: 1
  forwardPort: 31000
  measurementPort: 32000
  keysDir: keys/proxy
  maxOwd: 10000

# Receiver Info
receiver:
  ips: 
  - "10.128.0.6"
  - "10.128.0.7"
  - "10.128.0.8"
  - "10.128.0.9"
  port: 33000
  keysDir: keys/receiver
  shards: 1 # The number of threads to receive threads 
  local: true


# Replica Info
replica:
  ips: 
  - "10.128.0.6"
  - "10.128.0.7"
  - "10.128.0.8"
  - "10.128.0.9"
  port: 34000
  keysDir: "keys/replica"
  fallbackTimeout: 2000000
  fallbackStartTimeout: 500000

