transport: "nng"

client:
  ips: 
  - "10.128.0.13"
  - "10.128.0.5"
  port: 33000
  keysDir: keys/client
  maxRequests: 1
  numRequests: 1000000
  runtimeSeconds: 60 
  normalPathTimeout: 5000
  slowPathTimeout: 500000


# Proxy Info
proxy:
  ips: 
    - "10.128.0.17"  
    - "10.128.0.19"  
  shards: 1
  forwardPort: 31000
  measurementPort: 32000
  keysDir: keys/proxy
  maxOwd: 10000

# Receiver Info
receiver:
  ips: 
  - "10.128.0.6"
  - "10.128.0.7"
  - "10.128.0.8"
  - "10.128.0.9"
  port: 33000
  keysDir: keys/receiver
  shards: 1 # The number of threads to receive threads 
  local: true


# Replica Info
replica:
  ips: 
  - "10.128.0.6"
  - "10.128.0.7"
  - "10.128.0.8"
  - "10.128.0.9"
  port: 34000
  keysDir: "keys/replica"
  fallbackTimeout: 2000000
  fallbackStartTimeout: 500000

