transport: udp

client:
  ips:
  - 10.138.0.6
  - 10.182.0.4
  - 10.142.0.4
  - 10.202.0.3
  keysDir: keys/client
  maxRequests: 5
  numRequests: 1000000
  runtimeSeconds: 20 
  port: 33000
  normalPathTimeout: 100000
  slowPathTimeout:   2000000
  sendRate: 100
  
proxy:
  forwardPort: 31000
  ips:
  - 10.138.0.5
  - 10.182.0.3
  - 10.142.0.3
  - 10.150.0.2
  keysDir: keys/proxy
  maxOwd: 100000
  measurementPort: 32000
  shards: 1

receiver:
  ips:
  - 10.138.0.4
  - 10.142.0.2
  - 10.182.0.2
  - 10.202.0.2
  keysDir: keys/receiver
  local: true
  port: 33000
  shards: 1

replica:
  ips:
  - 10.138.0.4
  - 10.142.0.2
  - 10.182.0.2
  - 10.202.0.2
  keysDir: keys/replica
  port: 34000
  fallbackTimeout: 2000000
  fallbackStartTimeout: 500000
