transport: nng 

app: "kv_store"

client:
  ips:
  - 10.138.0.15
  - 10.142.0.14
  - 10.150.0.12
  - 10.182.0.13
 
  keysDir: keys/client
  maxInFlight: 100
  port: 33000
  runtimeSeconds: 22
  
  sendMode: maxInFlight
  maxInFlight: 100
  sendRate: 300
  requestSize: 512

  normalPathTimeout: 200000
  slowPathTimeout: 1000000
  requestTimeout: 1000000     # 1 s

proxy:
  forwardPort: 31000
  ips:
  - 10.138.0.15
  - 10.142.0.14
  - 10.150.0.12
  - 10.182.0.13
  keysDir: keys/proxy
  maxOwd: 100000
  measurementPort: 32000
  shards: 1

receiver:
  ips:
  - 10.138.0.14
  - 10.142.0.13
  - 10.150.0.11
  - 10.182.0.12
  keysDir: keys/receiver
  local: true
  numVerifyThreads: 6
  port: 33000
  shards: 1

replica:
  repairTimeout: 5000000
  repairViewTimeout: 10000000
  ips:
  - 10.138.0.14
  - 10.142.0.13
  - 10.150.0.11
  - 10.182.0.12
  keysDir: keys/replica
  numSendThreads: 6
  numVerifyThreads: 6
  port: 34000

  checkpointInterval: 2000
