transport: nng

client:
  ips:
  - 10.138.0.6
  - 10.182.0.4
  - 10.142.0.4
  - 10.202.0.3
  keysDir: keys/client
  maxRequests: 20
  numRequests: 1000
  port: 33000
  normalPathTimeout: 100000
  slowPathTimeout:   1000000



proxy:
  forwardPort: 31000
  ips:
  - 10.138.0.5
  - 10.182.0.3
  - 10.142.0.3
  keysDir: keys/proxy
  maxOwd: 200000
  measurementPort: 32000
  shards: 1
receiver:
  ips:
  - 10.138.0.4
  - 10.142.0.2
  - 10.182.0.2
  - 10.202.0.2
  keysDir: keys/receiver
  local: true
  port: 33000
  shards: 1
replica:
  ips:
  - 10.138.0.4
  - 10.142.0.2
  - 10.182.0.2
  - 10.202.0.2
  keysDir: keys/replica
  port: 34000

