transport: nng 

app: "counter"

client:
  ips: 
  - 10.138.0.6
  - 10.182.0.4
  - 10.142.0.4
  - 10.202.0.5

  # - 10.138.0.8 
  # - 10.182.0.6
  # - 10.142.0.6
  # - 10.150.0.3
  keysDir: keys/client
  port: 33000
  normalPathTimeout: 200000   # 200 ms
  slowPathTimeout:   1000000  # 1 s

  sendMode: "maxInFlight"
  maxInFlight: 100
  sendRate: 300
  runtimeSeconds: 15

proxy:
  forwardPort: 31000
  ips:
  - 10.138.0.7
  - 10.182.0.5
  - 10.142.0.5
  - 10.202.0.4
  keysDir: keys/proxy
  shards: 1 
  maxOwd: 100000
  measurementPort: 32000

receiver:
  ips:
  - 10.138.0.4
  - 10.182.0.2
  - 10.142.0.2
  - 10.202.0.2
  keysDir: keys/receiver
  local: true
  port: 33000
  shards: 1
  numVerifyThreads: 6

replica:
  ips:
  - 10.138.0.4
  - 10.182.0.2
  - 10.142.0.2
  - 10.202.0.2
  keysDir: keys/replica
  port: 34000
  fallbackTimeout: 5000000
  fallbackStartTimeout: 500000
  numVerifyThreads: 2
  numSendThreads: 6
