transport: nng 

app: "counter"

client:
  ips: 
  - 10.138.0.6

  keysDir: keys/client
  port: 33000
  normalPathTimeout: 100000   # 100 ms
  slowPathTimeout:   1000000  # 1 s

  sendMode: "sendRate"
  maxInFlight: 500
  sendRate: 4000
  runtimeSeconds: 30

proxy:
  forwardPort: 31000
  ips:
  - 10.138.0.7
  keysDir: keys/proxy
  maxOwd: 100000
  measurementPort: 32000
  shards: 1

receiver:
  ips:
  - 10.138.0.4
  - 10.182.0.2
  keysDir: keys/receiver
  local: true
  port: 33000
  shards: 1

replica:
  ips:
  - 10.138.0.4
  - 10.182.0.2
  keysDir: keys/replica
  port: 34000
  fallbackTimeout: 5000000
  fallbackStartTimeout: 500000
