
# Replica Info
replicaIps:
  - "127.0.0.1"
  - "127.0.0.2"
  - "127.0.0.3"
  - "127.0.0.4"
replicaKeysDir: "keys/replicas"
replicaKey: "keys/replicas/replica0.pem"
replicaPort: 34000

# Client Info
clientIps: 
  - "127.0.0.7"
clientKeysDir: keys/clients
clientPort: 33000


# Proxy Info
useProxy: true

proxyKeysDir: keys/proxies
receiverKeysDir: keys/receivers